config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  resources :steps, except: [:new]
  get '/steps/:candidate_id/new', to: 'steps#new', as: :new_step
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'candidates#index'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :recruiter, class_name: "User"
  belongs_to :owner, class_name: "User"
  has_many :steps

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@([a-z\d\-]+\.)+[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :phone, presence: true, uniqueness: { case_sensitive: false }
  validates :resume_url, presence: true, uniqueness: { case_sensitive: false }

  def alias
    # recruiter.name.split(" ").each {|n| n.first}.join + id.to_s
    name
  end
  
  def to_s
    self.alias
  end
    
  def next_step
    Step.where(candidate: self).last
  end

  def owner
    next_step.owner
  end

  def owner=(user)
    next_step.update_attribute(:owner, user)
  end
  
  def urgency
    if steps.last.updated_at > 30.minutes.ago
      "normal"
    elsif steps.last.updated_at > 1.hour.ago
      "medium"
    else
      "high"
    end
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :candidate, class_name: "Candidate"
  belongs_to :owner, class_name: "User"
  default_scope { order('id ASC') }
  
  validates :description, presence: true
  validates :owner, presence: true

  def to_s
    description
  end
  
  def next
    self.class.where(candidate: candidate).where("id != ?", id).first
  end
  
  # XXX Why did this not work with after_commit?
  after_save do
    if new_record? || owner_id_changed?
      rv = Notifications.became_owner(self).deliver
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true
  before_create :create_remember_token

  before_save do
    self.email.downcase!
  end
  
  def to_s
    name
  end

  def User.new_secure_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  # Set the user signed in and return the remember token for the cookie
  def try_sign_in(password)
    if authenticate(password)
      remember_token = User.new_secure_token
      self.remember_token = User.digest(remember_token)
    else
      remember_token = nil
    end
    save
    remember_token
  end

  def sign_out
    update_attribute(:remember_token, User.digest(User.new_secure_token))
  end

  def confirm(token)
    if User.digest(token) == confirmation_digest
      update_attribute(:confirmed, true)
    end
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_secure_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :require_signin

  def index
    candidates = Step.where(owner: current_user).map do |s| 
      s.candidate
    end.reject {|c| c.inactive? }.uniq
    @todo, @other = candidates.partition do |candidate|
      candidate.owner == current_user
    end
  end

  def show
    @candidate = Candidate.find(params[:id])
    steps = @candidate.steps
    @step = steps.last
    @history = steps[0...-1]
  end
  
  def new
    @candidate = Candidate.new
  end

  def create
    Candidate.transaction do
      Step.transaction do
        @candidate = Candidate.new(candidate_params)
        if @candidate.save
          first_step = Step.new(candidate: @candidate,
                                owner: @candidate.recruiter,
                                description: 'Triage candidate')
          if first_step.save
            flash[:success] = "#{@candidate} created!"
            redirect_to @candidate
            return
          end
        end
        @errors = @candidate.errors
        render 'new' # Try again
      end
    end
  end
  
  def edit
    @candidate = Candidate.find(params[:id])
  end
  
  def update
    @candidate = Candidate.find(params[:id])
    if @candidate.update_attributes(candidate_params)
      flash[:success] = "Update successful"
      redirect_to @candidate
    else
      @errors = @candidate.errors
      render 'edit' # Try again
    end
  end

  private

    def candidate_params
      params.require(:candidate).permit(:name, :email, :resume_url, :phone, :recruiter_id, :inactive)
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && sign_in(user, params[:session][:password])
      flash[:success] = "Hello, #{current_user.name}!"
      url = session.delete(:pre_signin_url)
      redirect_to url || candidates_path
    else
      flash.now[:error] = 'Wrong password or email'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :require_signin
  before_action :check_owner

  def update
    @step = Step.find(params[:id])
    if @step.update_attributes(step_params)
      flash[:success] = "Update successful"
      if params[:commit] == "Update"
        redirect_to :back
      elsif params[:commit] == "Send to next step"
        redirect_to new_step_path(@step.candidate)
      end
    else
      # broken
      raise
      # @errors = @step.errors
      # CandidatesController.find(@step.candidate.id, @step)
      # render 'candidates/show' # Try again
    end
  end
  
  def new
    @step = Step.new(candidate_id: params[:candidate_id])
  end

  def create
    @step = Step.new(step_params)
    if @step.save
      flash[:success] = "Now it's #{@step.owner}'s problem!"
      redirect_to @step.candidate
    else
      @errors = @step.errors
      render 'new' # Try again
    end
  end
  
  private

    def step_params
      params.require(:step).permit(:description, :notes, :candidate_id, :owner_id)
    end
    
    def check_owner
      if params[:action] == 'new'
        candidate = Candidate.find(params[:candidate_id])
        step = candidate.steps.last
      elsif params[:action] == 'create'
        candidate = Candidate.find(params[:step][:candidate_id])
        step = candidate.steps.last
      else
        step = Step.find(params[:id])
      end
      if step && step.owner != current_user
        redirect_to root_url, notice: "You don't have the rights to do that."
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # This hits the DB for every pageload; we can do better
  def sign_in(user, password)
    remember_token = user.try_sign_in(password)
    if remember_token
      cookies.permanent[:remember_token] = remember_token
      self.current_user = user
    end
  end

  def sign_out(user=current_user)
    user.sign_out
    if user == current_user
      cookies.delete(:remember_token)
      self.current_user = nil
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= find_user_by_cookie
  end

  def current_user_owns?(obj)
    current_user && current_user.id == obj.user.id
  end

  def require_signin
    unless signed_in?
      session[:pre_signin_url] = request.url
      redirect_to signin_path, notice: "You must sign in to do that."
    end
  end

  def check_authorization
    if params.include?(:id) && params[:id].to_i != current_user.id
      raise
      redirect_to root_url, notice: "You don't have the rights to do that."
    end
  end

  private

    def find_user_by_cookie
      remember_token_digest = User.digest(cookies.permanent[:remember_token])
      User.find_by_remember_token(remember_token_digest)
    end
end

app/helpers/step_helper.rb
module StepHelper
end

app/views/candidates/_candidate.html.erb
<li class="<%= candidate.urgency%>">
  <%= link_to candidate.name, candidate %>
  <%= mail_to candidate.email %>
  <%= candidate.phone %>
  Next step: <%= candidate.next_step %>
  Owner: <%= candidate.owner.name %>
  Last updated: <%= time_ago_in_words(candidate.next_step.updated_at) %> ago
</li>

app/views/candidates/_candidate_form.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@candidate) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :phone %>
      <%= f.text_field :phone %>

      <%= f.label :resume_url %>
      <%= f.text_field :resume_url %>

      <%= f.label :recruiter %>
      <%= f.select :recruiter_id,
        options_from_collection_for_select(User.all, :id, :name,
                                           selected: @candidate.recruiter_id),
        prompt: "Throat to choke?" %>

      <%= f.submit yield(:submit_text), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/candidates/edit.html.erb
<% provide(:title, 'Edit Candidate') %>
<% provide(:submit_text, 'Update') %>

<h1>Edit Candidate</h1>

<%= render 'candidate_form' %>

app/views/candidates/index.html.erb
<strong>Candidates to act on</strong>
<ul>
  <%= render partial: "candidate", collection: @todo %>
</ul>
<strong>Candidates of interest</strong>
<ul>
  <%= render partial: "candidate", collection: @other %>
</ul>

app/views/candidates/new.html.erb
<% provide(:title, 'Create Candidate') %>
<% provide(:submit_text, 'Create') %>

<h1>Create Candidate</h1>

<%= render 'candidate_form' %>

app/views/candidates/show.html.erb
<div class="jumbotron">
  <div class="row"><strong><%= @candidate.alias %></strong></div>
  <div class="row">Recruiter: <%= @candidate.recruiter.name %></div>
  <div class="row">Owner: <%= @candidate.owner.name %></div>
  <div class="row">Résumé: <%= link_to @candidate.resume_url, @candidate.resume_url %></div>
  <div class="row">Contact: <%= @candidate.phone %> <%= mail_to @candidate.email, "Email" %></div>
  <%= link_to "Edit Details", edit_candidate_path(@candidate) %>
</div>

<% if @candidate.owner == current_user %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@step) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :notes %>
      <%= f.text_area :notes %>

      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
      <%= f.submit "Send to next step", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<% else %>
  <div class="row">Next step: <%= @step.description %></div>
  <div class="row">Status: <%= @step.notes %></div>
  <div class="row">Last updated: <%= time_ago_in_words(@step.updated_at) %> ago</div>
<% end %>

<div class="row">History:</div>

<ol>
  <% @history.each do |step| %>
      <li>
        Started: <%= time_ago_in_words(step.created_at) %> ago,
        completed: <%= distance_of_time_in_words(step.next.created_at - step.created_at) %> later
        <ul>
          <li><%= step.description %></li>
          <li><%= step.notes %></ll>
        </ul>
      </li>
  <% end %>
</ol>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Jon Bauman & David Kushi
  </small>
  <nav>
    <ul>
      <li>Problems, questions, etc: <%= mail_to "jon.bauman@isilon.com" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Red Hunting Cap", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Add Candidate", "/candidates/new" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Red Hunting Cap | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(current_user) if Rails.env.development? %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/notifications/became_owner.html.erb
<h1>Congratulations, it's a candidate!</h1>

<p>
  Hello <%= @user %>,<br /> you are now the current owner of <%= @candidate %> and you are expected to "<%= @step %>". Please do that and <%= link_to "report your status", candidate_url(@candidate) %>.
</p>
<p>
  Thanks, love Karl.
</p>

app/views/notifications/became_owner.text.erb
Notifications#became_owner

<%= @greeting %>, find me in app/views/notifications/became_owner.text.erb

app/views/notifications/candidate_updated.html.erb
<h1>Notifications#candidate_updated</h1>

<p>
  <%= @greeting %>, find me in app/views/notifications/candidate_updated.html.erb
</p>

app/views/notifications/candidate_updated.text.erb
Notifications#candidate_updated

<%= @greeting %>, find me in app/views/notifications/candidate_updated.text.erb

app/views/shared/_error_messages.html.erb
<% if @errors && @errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@errors.count, "error") %>.
    </div>
    <ul>
    <% @errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/steps/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@step) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.hidden_field :candidate_id, value: @step.candidate.id %>

      <%= f.label :owner %>
      <%= f.select :owner_id,
        options_from_collection_for_select(User.all, :id, :name),
        prompt: "Throat to choke?" %>

      <%= f.submit "Transition to next step", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>